title: Stratigraphic Guide
email: nicholas.car@surroundaustralia.com
description: >-
  Effective communication in science requires accurate and precise internationally acceptable terminology and procedures. The Abridged Version of the International Stratigraphic Guide, like the Guide itself, was developed to promote international agreement on principles of stratigraphic classification and to develop an internationally acceptable stratigraphic terminology and rules of procedure in the interest of improved accuracy and precision in international communication, coordination, and understanding. It is not a revision of the Guide but a short version that omits history, explanatory text, and exemplification, the glossaries and the bibliography.
baseurl: "/guide"
url: "https://stratigraphy.org"
github_username:  nicholascar

# Build settings
theme: minima
plugins:
  - jekyll-feed


exclude:
  - README.md
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
